name: Metrics
on:
  schedule: [{cron: "0 */8 * * *"}] # Se ejecuta cada 8 horas
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # TU NUEVO TOKEN
          token: ${{ secrets.METRICS_TOKEN }}

          # APARIENCIA Y PLUGINS MEJORADOS
          user: JoelVR1307
          template: classic
          config_timezone: America/Lima
          
          # Plugins para un look más completo y atractivo
          base: header, activity, community, repositories, metadata
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_lines: yes
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_charts: yes
          plugin_habits_trim: yes
